# [hooks]
# pre-commit = ["cargo fmt"]
# # pre-push = ["cargo fmt", "cargo make cov"]

# [logging]
# verbose = true

[hooks]
pre-commit = "cargo test"
pre-push = ["cargo check", "cargo fmt -- --check"]
post-commit = "echo yay"

[logging]
verbose = true