[tasks.cov]
script_runner = "bash"
script = '''
export CARGO_INCREMENTAL=0
export RUSTFLAGS='-Cinstrument-coverage'
export LLVM_PROFILE_FILE='llvm/cargo-test-%p-%m.profraw'
cargo test
rm -rf coverage/
grcov . --binary-path ./target/debug/deps/ -s . -t html --branch --ignore-not-existing --ignore '../*' --ignore '/*' -o coverage/
'''